## Metode numerice de rezolvare a sistemelor liniare

1. Să se verifice dacă sistemul (1) admite soluție unică și în caz afirmativ să se determine soluția folosind metoda Gauss cu pivotare totală.

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 
$ \begin{bmatrix} 0 & 3 & -1 & 0 \\ -1 & 8 & -1 & -2 \\ -4 & -10 & 9 & 3 \\ -4 & 5 & -8 & -10 \end{bmatrix} x  = \begin{bmatrix} 3 \\ 4 \\ 15 \\ -58 \end{bmatrix}$ &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp;  $(1)$

&emsp; &ensp;  Sistemul pătratic adminte soluție unică dacă și numai dacă determinantul matricei asociat sistemului este nenul.

In [11]:
import numpy as np

A = np.array([[0., 3., -1., 0.], [-1., 8., -1., -2.], [-4., -10., 9., 3.], [-4., 5., -8., -10.]], dtype = np.float64)
b = np.array([[3., 4., 15., -58.]], dtype = np.float64).T
x = np.array([[0., 0., 0., 0.]], dtype = np.float64).T

n = A.shape[0]

# Verificam daca sistemul are solutii
if abs(np.linalg.det(A)) < 1e-5:
    print("Determinantul matricei este null, prin urmare sistemul este incompatibil sau compatibil nedeterminat!")
else:
    # Aplicam metoda Gauss cu pivotare totala
    indices = np.arange(0, n)
    A_extins = np.concatenate((A, b), axis = 1)

    """ 
        La fiecare pas al algoritmului alegem ca pivot elementul cu valoarea absoluta cea mai mare din submatricea
        A_extins[k:, k:n], unde A_extins este matricea extinsa asociata sistemului
    """    
    for k in range(0, n - 1):
        submatrice = A_extins[k:, k:n-1]
        (p, m) = np.unravel_index(submatrice.argmax(), submatrice.shape)
        p, m = p + k, m + k

        # Daca p != k atunci interschimbam liniile p si k, iar daca m != k interschimbam coloanele m si k
        A_extins[[p,k]] = A_extins[[k,p]]
        A_extins[:, [k, m]] = A_extins[:, [m, k]]
        # Schimbam indicii necunoscutelor
        indices[[k, m]] = indices[[m, k]]

        for l in range(k + 1, n):
            A_extins[l] = A_extins[l] - (A_extins[l][k] / A_extins[k][k]) * A_extins[k]


    U = np.copy(A_extins[0:n])
    U = np.delete(U, n, axis = 1)
    C = A_extins[:,n]
    
     
    """
        Mergem de la ultima linie catre prima, rezolvand sistemul prin substitutie (Metoda substitutiei descendente)
    """
    for i in range(n-1, -1, -1):
        x[i] = (C[i] - np.dot(U[i,i+1:], x[i+1:])) / U[i][i]

    # La interschimbarea a doua coloane se schimba ordinea necunoscutelor in vectorul x
    x = x[indices]
    
    print('x = ')
    print(x)
    print('A @ x = \n', A @ x )

x = 
[[1.]
 [2.]
 [3.]
 [4.]]
A @ x = 
 [[  3.]
 [  4.]
 [ 15.]
 [-58.]]


2. Verificați dacă matricea B este inversabilă și în caz afirmativ aplicați metoda Gauss pentru determinarea inversei.

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
 $ B = \begin{bmatrix} 0 & 4 & 6 & 9 \\ 6 & 4 & 9 & 9 \\ -4 & 3 & -6 & 9 \\ -10 & 7 & -8 & 1 \end{bmatrix} $ &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; $ (2) $

&emsp; &ensp; Matricea B este inversabilă dacă și numai dacă este o matrice nesingulară, adică determinantul său este nenul. Pentru a calcula determinantul matricei B putem folosi metoda Gauss cu pivotare totală.

In [12]:
import numpy as np

# Aplicatii ale metodei Gauss --- Calcularea determinantului unei matrice
B = np.array([[0., 4., 6., 9.], [6. , 4., 9., 9.], [-4., 3., -6., 9.], [-10., 7, -8, 1]])
n = A.shape[0]
x = np.zeros(A.shape)
I = np.identity(n, dtype=float)

# Aplicam metoda Gauss cu pivotare totala
indices = np.arange(0, n)
B_extins = np.concatenate((B, I), axis = 1)
s = 0 # numarul de schimbari de linii

for k in range(0, n - 1):
    submatrice = B_extins[k:, k:n-1]
    (p, m) = np.unravel_index(submatrice.argmax(), submatrice.shape)
    p, m = p + k, m + k
    
    if p != k:
        s += 1
    
    if m != k:
        s += 1

    # Daca p != k atunci interschimbam liniile p si k, iar daca m != k interschimbam coloanele m si k
    B_extins[[p,k]] = B_extins[[k,p]]
    B_extins[:, [k, m]] = B_extins[:, [m, k]]
    # Schimbam indicii necunoscutelor
    indices[m], indices[k] = indices[k], indices[m]

    for l in range(k + 1, n):
        B_extins[l] = B_extins[l] - (B_extins[l][k] / B_extins[k][k]) * B_extins[k]

        
U = np.copy(B_extins[0:n])

determinant = 1.
for i in range(n):
    determinant *= U[i][i]

"""
    Daca intr-o matrice patratica se schimba intre ele doua linii(sau coloane) se obtine o matrice care are
    determinantul egal cu opusul determinantului matricei initiale
"""
determinant = (-1)**s * determinant
print('Determinantul matricei obtinut folosind Gauss cu pivotare totala: ', determinant)
print('Determinantul matricei folosind np.linalg.det: ', np.linalg.det(B))

Determinantul matricei obtinut folosind Gauss cu pivotare totala:  -3738.0000000000005
Determinantul matricei folosind np.linalg.det:  -3737.999999999998


&emsp; Inversa matricei $ B^{-1} $ verifică relația:
    $$ B^{-1} B = B B^{-1} = I_n $$

&emsp; Fie $ x^{k} \in \mathbb{R}^{n}, k \in [1,n] $ coloana k a matricei $ B^{-1} $. De asemenea, fie $ e^{k} \in \mathbb{R}^{n}, e^{k} = (0,...,1...,0)^{T} $, cu 1 pe pozitita k, coloana k din matricea $I_n.$ Atunci 

&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;  &emsp; $ B B^{-1} = I_n \Leftrightarrow A x^{k} = e^{k} $ &emsp;, $k = \overline{1,n} $

&emsp; Pentru a rezolva simultan cele n sisteme liniare în care vectorii necunoscutelor sunt coloanele inversei, considerăm drept matrice extinsă, matricea formată din matricea B la care se adaugă cele n coloane ale matricei $ I_n $ si calculăm necunoscutele conform unei metode de pivotare, fie de exemplu, metoda _Gauss cu pivotare parțială_.

In [16]:
def pprint(A):
    n = A.shape[0]
    for i in range(0, n):
        line = ""
        for j in range(0, 2*n):
            line += str(A[i][j]) + "\t"
            if j == n - 1:
                line += "|  "
        print(line)
    print("")

# Verificam daca sistemul are solutii(determinantul matricei trebuie sa fie diferit de 0)
if abs(np.linalg.det(B)) < 1e-5:
    print("Determinantul matricei este null, prin urmare matricea nu este inversabila!")
else:
    A = np.array([[0., 4., 6., 9.], [6. , 4., 9., 9.], [-4., 3., -6., 9.], [-10., 7, -8, 1]])
    n = A.shape[0]
    x = np.zeros(A.shape)
    I = np.identity(n, dtype=float)

    indices = np.arange(0, n)
    A_extins = np.concatenate((A, I), axis = 1)
    print('Matricea extinsă: ')
    pprint(A_extins)
    
    # Aplicam Gauss cu pivotare partiala
    for k in range(0, n-1):
        p = np.argmax(np.abs(A_extins[k:, k])) + k
        A_extins[[p,k]] = A_extins[[k,p]] 
        for l in range(k + 1, n):
            A_extins[l] = A_extins[l] - (A_extins[l][k] / A_extins[k][k]) * A_extins[k]
        
    # Aducem matricea din partea stanga la forma matricei identitate, 
    # iar ce obtinem in partea dreapta va fi inversa matricei initiale   
    for i in range(n-1, 0, -1):
        A_extins[i] *= 1. / A_extins[i][i]
        for j in range(i-1, -1, -1):
            A_extins[j] = A_extins[j] - (A_extins[j][i] / A_extins[i][i]) * A_extins[i]
    
    A_extins[0] *= 1. / A_extins[0][0]
   
    print('Inversa matricei B: ')
    print(A_extins[:,n:])

Matricea extinsă: 
0.0	4.0	6.0	9.0	|  1.0	0.0	0.0	0.0	
6.0	4.0	9.0	9.0	|  0.0	1.0	0.0	0.0	
-4.0	3.0	-6.0	9.0	|  0.0	0.0	1.0	0.0	
-10.0	7.0	-8.0	1.0	|  0.0	0.0	0.0	1.0	

Inversa matricei B: 
[[-0.25842697  0.21027287  0.04735152  0.00722311]
 [-0.16853933  0.20545746 -0.0529695   0.14446228]
 [ 0.1835206  -0.08721241 -0.09470305 -0.01444623]
 [ 0.06367041 -0.03317282  0.08667737 -0.05457464]]


3. Să se verifice dacă sistemul (3) admite soluție unică și în caz afirmativ să se determine soluția folosind factorizarea
LU cu pivotare partială.

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
$ \begin{bmatrix} 0 & -4 & -4 & 5 \\ 5 & -7 & 9 & -4 \\ 0 & -1 & -10 & 9 \\ -6 & 6 & -5 & 3 \end{bmatrix} x  = \begin{bmatrix} -3 \\ 5 \\ 2 \\ 1 \end{bmatrix}$ &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; $ (3) $

&emsp; Sistemul (3) este de forma $$ Ax=b $$ cu $ A \in \mathscr{M}_{4}(R) $ și $ b, x \in R^{4}.$ <br>
&emsp; Sistemul $ Ax = b $ este compatibil determinat, i.e. admite o soluție unică dacă și numai dacă $ rangA = rang\overline{A} = 4$ (numărul necunoscutelor).

In [14]:
import numpy as np
from copy import deepcopy

A = np.array([[0., -4., -4., 5.], [5., -7., 9., -4.], [0., -1., -10., 9.], [-6., 6., -5., 3.]])
b = np.array([[-3. , 5., 2., 1.]]).T
A_extins = np.concatenate((A,b), axis = 1)
P = np.identity(n)

n = A.shape[0]
x = np.zeros(n)


# Calculul rangului unei matrice cu ajutorul metodei Gauss cu pivotare partiala
def determina_rang(A, toleranta = 1e-5):
    m, n = A.shape[0], A.shape[1]
    
    # Se initializeaza linia, coloana si rangul
    l, c, rang = 0, 0, 0
    while l < m and  c < n:
        pivot = np.argmax(np.abs(A[l:,c])) + l
        if np.abs(A[pivot][c]) < toleranta:
            c = c + 1
            continue
        
        if pivot != l:
            A[[l,pivot]] = A[[pivot,l]]
        
        # Se elimina elementele sub pivot
        for i in range(l+1,m):
            const = A[i][c] / A[l][c]
            A[i] = A[i] - const * A[l]
        
        l += 1 # Se avanseaza pe linii
        c += 1 # Se avanseaza pe coloane
        rang += 1 # Se creste rangul

    return rang


# Gauss cu pivotare partiala
def factorizare(A):
    U = np.copy(A) # matricea superior triunghiulara
    L = np.zeros(A.shape) # matricea inferior triunghiulara
    for k in range(0, n-1):
        p = np.argmax(np.abs(U[k:,k]))
        p = p + k
        # interschimbam liniile p si k in U, P, L
        U[[p,k]] = U[[k,p]]
        P[[p,k]] = P[[k,p]] 
        L[[p,k]] = L[[k,p]]
        for i in range(k + 1, n):
            L[i][k] = U[i][k] / U[k][k]
            U[i] = U[i] - (L[i][k] * U[k])
    L += np.identity(n)
    
    print('U: \n', U)
    print('L: \n', L)
    print('\n P @ A == L @ U:')
    print( P @ A == L @ U, '\n')
    
    return L, U


# Metoda Substitutiei Ascendente
def metoda_substitutiei_ascendente(L, C):
    y = np.zeros(n)
    for i in range(0, n):
        y[i] = (C[i] - np.dot(L[i,:i+1], y[:i+1])) / L[i,i]
    return y


# Metoda Substitutiei Descendente
def metoda_substitutiei_descendente(U, C):
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (C[i] - np.dot(U[i,i+1:], x[i+1:])) / U[i][i]
    return x


if __name__ == "__main__":
    rang_A = determina_rang(deepcopy(A))
    rang_A_extins = determina_rang(deepcopy(A_extins))

    if rang_A == rang_A_extins and rang_A == n:
        print('Sistemul este compatibil determinat.')
        L, U = factorizare(deepcopy(A)) # obtinem factorizarea LU a matricei A
        
        b = P @ b
        y = metoda_substitutiei_ascendente(L, b)
        x = metoda_substitutiei_descendente(U, y)
        print('x = ', x)
        print('A @ x = ', A@x)

    elif rang_A != rang_A_extins:
        print('Sistemul este incompatibil.')
    else:
        print('Sistemul este compatibil nedeterminat.')

Sistemul este compatibil determinat.
U: 
 [[-6.          6.         -5.          3.        ]
 [ 0.         -4.         -4.          5.        ]
 [ 0.          0.         -9.          7.75      ]
 [ 0.          0.          0.          1.88425926]]
L: 
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.25        1.          0.        ]
 [-0.83333333  0.5        -0.75925926  1.        ]]

 P @ A == L @ U:
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

x =  [2. 3. 4. 5.]
A @ x =  [-3.  5.  2.  1.]


4. Să se verifice dacă matricea C admite factorizare Cholesky și în caz afirmativ să se determine aceasta.

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
 $ C = \begin{bmatrix} 64 & 16 & 72 & -40 \\ 16 & 104 & -52 & 80 \\ 72 & -52 & 211 & -90 \\ -40 & 80 & -90 & 135 \end{bmatrix} $ &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; $ (4) $

&emsp; Dacă $ C \in \mathscr{M}_4(\mathbb{R}) $ este o matrice simetrică și pozitiv definită, atunci descompunerea Cholesky există. Se poate observa că $ C = C^{T} $. Întrucât C este simetrică, o condiție necesară și suficientă ca C să fie pozitiv definită, este ca toți minorii principali să fie pozitivi, i.e $ detA_k > 0, A_k = (a_{ij})_{i,j=\overline{1,k}} $ .

In [15]:
from sys import exit
import numpy as np
from copy import deepcopy


C = np.array([[64., 16., 72., -40.], [16., 104., -52., 80.], [72., -52., 211., -90.], [-40., 80., -90., 135.]])
C_transpus = np.array([[64., 16., 72., -40.], [16., 104., -52., 80.], [72., -52., 211., -90.], [-40., 80., -90., 135.]]).T
n = C.shape[0]


def calculeaza_determinant(A):
    # Aplicam metoda Gauss cu pivotare totala
    m = A.shape[0]
    indices = np.arange(0, m)
    I = np.identity(m)
    A_extins = np.concatenate((A, I), axis = 1)
    s = 0 # numarul de schimbari de linii

    for k in range(0, m - 1):
        submatrice = A_extins[k:, k:m-1]
        (l, c) = np.unravel_index(submatrice.argmax(), submatrice.shape)
        l, c = l + k, c + k

        if l != k:
            s += 1

        if c != k:
            s += 1

        # Daca p != k atunci interschimbam liniile p si k, iar daca m != k interschimbam coloanele m si k
        A_extins[[l,k]] = A_extins[[k,l]]
        A_extins[:, [k, c]] = A_extins[:, [c, k]]
        # Schimbam indicii necunoscutelor
        indices[c], indices[k] = indices[k], indices[c]

        for i in range(k + 1, m):
            A_extins[i] = A_extins[i] - (A_extins[i][k] / A_extins[k][k]) * A_extins[k]


    U = np.copy(A_extins[0:n])

    determinant = 1.
    for i in range(m):
        determinant *= U[i][i]

    """
        Daca intr-o matrice patratica se schimba intre ele doua linii(sau coloane) se obtine o matrice care are
        determinantul egal cu opusul determinantului matricei initiale
    """
    determinant = (-1)**s * determinant
    
    return determinant


def factorizare_Cholesky(A):
    L = np.zeros(A.shape)
    
    alpha = A[0][0]
    L[0][0] = alpha**0.5
    for i in range(1,n):
        L[i][0] = A[i][0] / L[0][0]
        
    for k in range(1,n):
        alpha = A[k][k] - np.dot(L[k,:k], L[k,:k])
        L[k][k] = alpha**0.5
        
        for i in range(k+1,n):
            L[i][k] = (1.0 / L[k][k]) * (A[i][k] - np.dot(L[i,:k], L[k,:k]))
        
    return L


if __name__ == "__main__":
    
    if C.any() != C_transpus.any():
        print('Matricea nu este simetrica!')
        exit(1)
    
    for k in range(n):
        submatrice = deepcopy(C[:k+1][:k+1])
        det = calculeaza_determinant(submatrice)
        if det <= 0:
            print('Matricea nu este pozitiv definita!')
            exit(1)
    
    print('Matricea este simetrica si pozitiv definita, deci C admite factorizarea Cholesky. \n')
    L = factorizare_Cholesky(deepcopy(C))
    L_transpus = L.T
    print("L:")
    print(L)
    print("Transpusa matricei L: ")
    print(L_transpus)
    print("L @ L_transpus = C ")
    print(L @ L_transpus == C)

Matricea este simetrica si pozitiv definita, deci C admite factorizarea Cholesky. 

L:
[[ 8.  0.  0.  0.]
 [ 2. 10.  0.  0.]
 [ 9. -7.  9.  0.]
 [-5.  9.  2.  5.]]
Transpusa matricei L: 
[[ 8.  2.  9. -5.]
 [ 0. 10. -7.  9.]
 [ 0.  0.  9.  2.]
 [ 0.  0.  0.  5.]]
L @ L_transpus = C 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
