## L_03_1. Introduction to PyTorch Geometric

The aim of this notebook is to provide a very basic introduction to PyTorch geometric and to use the package for handling graphs. Have a look at https://pytorch-geometric.readthedocs.io/en/latest/get_started/introduction.html# 

In [2]:
%pip install torch_geometric

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 616.2/616.2 kB 9.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for torch_geometric: filename=torch_geometric-2.3.0-py3-none-any.whl size=909897 sha256=cdf626c71165b88748205a01445ff442298697231db5d43267211e72f5a5c5d7
  Stored in directory: /root/.cache/pip/wheels/cd/7d/6b/17150450b80b4a3656a84330e22709ccd8dc0f8f4773ba4133
Successfully built torch_geometric


In [3]:
# Define a graph by indicating the edges and weights of the nodes
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data1 = Data(x=x, edge_index=edge_index)

In [6]:
# Print / display data
print(data1)
print(data1.keys)
print(data1['x'])
for key, item in data1:
    print("{} found in data1".format(key))
data1.has_self_loops()

Data(x=[3, 1], edge_index=[2, 4])
['x', 'edge_index']
tensor([[-1.],
        [ 0.],
        [ 1.]], device='cuda:0')
x found in data1
edge_index found in data1


False

In [7]:
# Transfer data object to GPU.
device = torch.device('cuda')
data1 = data1.to(device)

In [8]:
# Define graph - alternative approach
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data2 = Data(x=x, edge_index=edge_index.t().contiguous())

In [11]:
# Print / display data
print(data2)
print(data2.keys)
print(data2['x'])
for key, item in data1:
    print("{} found in data2".format(key))
data2.contains_self_loops()

Data(x=[3, 1], edge_index=[2, 4])
['x', 'edge_index']
tensor([[-1.],
        [ 0.],
        [ 1.]])
x found in data2
edge_index found in data2


/usr/local/lib/python3.9/dist-packages/torch_geometric/deprecation.py:22: UserWarning: 'contains_self_loops' is deprecated, use 'has_self_loops' instead
  warnings.warn(out)


False

In [10]:
# Define my graph
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 0, 1, 2],
                           [1, 2, 2, 1]])
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)
data3 = Data(x=x, edge_index=edge_index.contiguous())

In [12]:
# Print / display data
print(data3)
print(data3.keys)
print(data3['x'])
for key, item in data1:
    print("{} found in data3".format(key))
data3.contains_self_loops()

Data(x=[3, 1], edge_index=[2, 4])
['x', 'edge_index']
tensor([[-1.],
        [ 0.],
        [ 1.]])
x found in data3
edge_index found in data3


/usr/local/lib/python3.9/dist-packages/torch_geometric/deprecation.py:22: UserWarning: 'contains_self_loops' is deprecated, use 'has_self_loops' instead
  warnings.warn(out)


False

In [13]:
# Define my graph
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 0, 1, 2, 2],
                           [1, 2, 2, 1, 2]])
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)
data3 = Data(x=x, edge_index=edge_index.contiguous())

# Print / display data
print(data3)
print(data3.keys)
print(data3['x'])
for key, item in data1:
    print("{} found in data3".format(key))
data3.contains_self_loops()

Data(x=[3, 1], edge_index=[2, 5])
['x', 'edge_index']
tensor([[-1.],
        [ 0.],
        [ 1.]])
x found in data3
edge_index found in data3


True